services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    # ports:
    #   - 5432:5432
  backend:
    build: ./Backend/
    depends_on:
      - db # Wait for DB service to start
    ports:
      - 3001:3001
  frontend:
    build: ./Frontend/todolistfrontend
    depends_on:
      - backend # Wait for backend service to start
    ports:
      - 3000:3000

